spring:
  datasource:
    password: ThePassword
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example
    username: springuser
  devtools:
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

